export const LARGE_CAP_STOCKS: string[] = [
  "360ONE", "ABB", "APLAPOLLO", "AUBANK", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ABCAPITAL", 
  "ALKEM", "AMBER", "AMBUJACEM", "ANGELONE", "APOLLOHOSP", "ASHOKLEY", "ASIANPAINT", "ASTRAL", "AUROPHARMA", "DMART", 
  "AXISBANK", "BSE", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BDL", 
  "BEL", "BHARATFORG", "BHEL", "BPCL", "BHARTIARTL", "BIOCON", "BLUESTARCO", "BOSCHLTD", "BRITANNIA", "CGPOWER", 
  "CANBK", "CDSL", "CHOLAFIN", "CIPLA", "COALINDIA", "COCHINSHIP", "COFORGE", "COLPAL", "CAMS", "CONCOR", 
  "CROMPTON", "CUMMINSIND", "DLF", "DABUR", "DALBHARAT", "DELHIVERY", "DIVISLAB", "DIXON", "DRREDDY", "ETERNAL", 
  "EICHERMOT", "EXIDEIND", "FORCEMOT", "NYKAA", "FORTIS", "GAIL", "GMRAIRPORT", "GLENMARK", "GODFRYPHLP", "GODREJCP", 
  "GODREJPROP", "GRASIM", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HAVELLS", "HEROMOTOCO", "HINDALCO", "HAL", 
  "HINDPETRO", "HINDUNILVR", "HINDZINC", "POWERINDIA", "HYUNDAI", "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDFCFIRSTB", "ITC", 
  "INDIANB", "IEX", "IOC", "IRFC", "IREDA", "INDUSTOWER", "INDUSINDBK", "NAUKRI", "INFY", "INOXWIND", 
  "INDIGO", "JINDALSTEL", "JSWENERGY", "JSWSTEEL", "JIOFIN", "JUBLFOOD", "KEI", "KPITTECH", "KALYANKJIL", "KAYNES", 
  "KFINTECH", "KOTAKBANK", "LTF", "LICHSGFIN", "LTM", "LT", "LAURUSLABS", "LICI", "LODHA", "LUPIN", 
  "M&M", "MANAPPURAM", "MANKIND", "MARICO", "MARUTI", "MFSL", "MAXHEALTH", "MAZDOCK", "MOTILALOFS", "MPHASIS", 
  "MCX", "MUTHOOTFIN", "NBCC", "NHPC", "NMDC", "NTPC", "NATIONALUM", "NESTLEIND", "NAM-INDIA", "NUVAMA", 
  "OBEROIRLTY", "ONGC", "OIL", "PAYTM", "OFSS", "POLICYBZR", "PGEL", "PIIND", "PNBHOUSING", "PAGEIND", 
  "PATANJALI", "PERSISTENT", "PETRONET", "PIDILITIND", "POLYCAB", "PFC", "POWERGRID", "PREMIERENE", "PRESTIGE", "PNB", 
  "RBLBANK", "RECLTD", "RVNL", "RELIANCE", "SBICARD", "SBILIFE", "SHREECEM", "SRF", "SAMMAANCAP", "MOTHERSON", 
  "SHRIRAMFIN", "SIEMENS", "SOLARINDS", "SONACOMS", "SBIN", "SAIL", "SUNPHARMA", "SUPREMEIND", "SUZLON", "SWIGGY", 
  "TATACONSUM", "TVSMOTOR", "TCS", "TATAELXSI", "TMPV", "TATAPOWER", "TATASTEEL", "TECHM", "FEDERALBNK", "INDHOTEL", 
  "PHOENIXLTD", "TITAN", "TORNTPHARM", "TRENT", "TIINDIA", "UNOMINDA", "UPL", "ULTRACEMCO", "UNIONBANK", "UNITDSPR", 
  "VBL", "VEDL", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "WIPRO", "YESBANK", "ZYDUSLIFE"
];

export const MIDCAP_STOCKS: string[] = [];

export const SMALLCAP_STOCKS: string[] = [];

export const INDICES = [
  "^NSEI",    // NIFTY 50 (Benchmark)
  "^CNX100",  // NIFTY 100 (Large Cap)
  "^NSMIDCP", // NIFTY MIDCAP 100
  "BSE-SMLCAP.BO",   // BSE SMALLCAP (Equivalent to NIFTY SMALLCAP 100)
];

export const RAW_UNIVERSE = [...LARGE_CAP_STOCKS, ...MIDCAP_STOCKS, ...SMALLCAP_STOCKS, "^NSEI", "^NSEBANK", "^BSESN"];
export const MARKET_UNIVERSE = [...RAW_UNIVERSE, ...INDICES];
export const NIFTY50 = LARGE_CAP_STOCKS;

export function getBenchmarkIndex(symbol: string): string {
  if (LARGE_CAP_STOCKS.includes(symbol)) return "^CNX100";
  if (MIDCAP_STOCKS.includes(symbol)) return "^NSMIDCP";
  if (SMALLCAP_STOCKS.includes(symbol)) return "BSE-SMLCAP.BO";
  return "^NSEI";
}
