export const FNO_STOCKS: string[] = [
  "360ONE", "ABB", "APLAPOLLO", "AUBANK", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ABCAPITAL", 
  "ALKEM", "AMBER", "AMBUJACEM", "ANGELONE", "APOLLOHOSP", "ASHOKLEY", "ASIANPAINT", "ASTRAL", "AUROPHARMA", "DMART", 
  "AXISBANK", "BSE", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BDL", 
  "BEL", "BHARATFORG", "BHEL", "BPCL", "BHARTIARTL", "BIOCON", "BLUESTARCO", "BOSCHLTD", "BRITANNIA", "CGPOWER", 
  "CANBK", "CDSL", "CHOLAFIN", "CIPLA", "COALINDIA", "COCHINSHIP", "COFORGE", "COLPAL", "CAMS", "CONCOR", 
  "CROMPTON", "CUMMINSIND", "DLF", "DABUR", "DALBHARAT", "DELHIVERY", "DIVISLAB", "DIXON", "DRREDDY", "ETERNAL", 
  "EICHERMOT", "EXIDEIND", "FORCEMOT", "NYKAA", "FORTIS", "GAIL", "GMRAIRPORT", "GLENMARK", "GODFRYPHLP", "GODREJCP", 
  "GODREJPROP", "GRASIM", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HAVELLS", "HEROMOTOCO", "HINDALCO", "HAL", 
  "HINDPETRO", "HINDUNILVR", "HINDZINC", "POWERINDIA", "HYUNDAI", "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDFCFIRSTB", "ITC", 
  "INDIANB", "IEX", "IOC", "IRFC", "IREDA", "INDUSTOWER", "INDUSINDBK", "NAUKRI", "INFY", "INOXWIND", 
  "INDIGO", "JINDALSTEL", "JSWENERGY", "JSWSTEEL", "JIOFIN", "JUBLFOOD", "KEI", "KPITTECH", "KALYANKJIL", "KAYNES", 
  "KFINTECH", "KOTAKBANK", "LTF", "LICHSGFIN", "LTM", "LT", "LAURUSLABS", "LICI", "LODHA", "LUPIN", 
  "M&M", "MANAPPURAM", "MANKIND", "MARICO", "MARUTI", "MFSL", "MAXHEALTH", "MAZDOCK", "MOTILALOFS", "MPHASIS", 
  "MCX", "MUTHOOTFIN", "NBCC", "NHPC", "NMDC", "NTPC", "NATIONALUM", "NESTLEIND", "NAM-INDIA", "NUVAMA", 
  "OBEROIRLTY", "ONGC", "OIL", "PAYTM", "OFSS", "POLICYBZR", "PGEL", "PIIND", "PNBHOUSING", "PAGEIND", 
  "PATANJALI", "PERSISTENT", "PETRONET", "PIDILITIND", "POLYCAB", "PFC", "POWERGRID", "PREMIERENE", "PRESTIGE", "PNB", 
  "RBLBANK", "RECLTD", "RVNL", "RELIANCE", "SBICARD", "SBILIFE", "SHREECEM", "SRF", "SAMMAANCAP", "MOTHERSON", 
  "SHRIRAMFIN", "SIEMENS", "SOLARINDS", "SONACOMS", "SBIN", "SAIL", "SUNPHARMA", "SUPREMEIND", "SUZLON", "SWIGGY", 
  "TATACONSUM", "TVSMOTOR", "TCS", "TATAELXSI", "TMPV", "TATAPOWER", "TATASTEEL", "TECHM", "FEDERALBNK", "INDHOTEL", 
  "PHOENIXLTD", "TITAN", "TORNTPHARM", "TRENT", "TIINDIA", "UNOMINDA", "UPL", "ULTRACEMCO", "UNIONBANK", "UNITDSPR", 
  "VBL", "VEDL", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "WIPRO", "YESBANK", "ZYDUSLIFE"
];

export const MTF_MARGINS: Record<string, number> = {
  "360ONE": 55, "3MINDIA": 60, "AARTIDRUGS": 55, "AARTIIND": 65, "AAVAS": 60, "ABB": 70, "ABBOTINDIA": 65, "ABCAPITAL": 50,
  "ABFRL": 60, "ABREL": 45, "ABSLAMC": 60, "ACC": 45, "ACCELYA": 50, "ACE": 50, "ACI": 65, "ACLGATI": 55, "ADANIENT": 35,
  "ADANIPORTS": 35, "ADFFOODS": 55, "ADVENZYMES": 55, "AETHER": 30, "AFFLE": 60, "AGARIND": 50, "AGI": 50, "AHLUCONT": 50,
  "AIAENG": 65, "AJANTPHARM": 65, "AKZOINDIA": 50, "ALEMBICLTD": 50, "ALKYLAMINE": 50, "ALKEM": 70, "ALLCARGO": 55,
  "AMBER": 50, "AMBUJACEM": 35, "AMIORG": 50, "AMRUTANJAN": 60, "ANDHRAPAP": 50, "ANDHRSUGAR": 55, "ANGELONE": 50,
  "ANURAS": 60, "APCOTEXIND": 55, "APEX": 50, "APLAPOLLO": 60, "APLTD": 70, "APOLLOHOSP": 70, "APOLLOPIPE": 60,
  "APOLLOTYRE": 50, "APTECHT": 35, "APTUS": 60, "ARMANFIN": 50, "ARVIND": 40, "ARVINDFASN": 60, "ASAHIINDIA": 50,
  "ASHIANA": 60, "ASHOKA": 65, "ASHOKLEY": 70, "ASIANPAINT": 70, "ASTEC": 60, "ASTERDM": 60, "ASTRAL": 70,
  "ASTRAMICRO": 55, "ASTRAZEN": 45, "ATUL": 65, "AUBANK": 65, "AUROPHARMA": 65, "AUTOAXLES": 50, "AUTOIND": 60,
  "AVADHHSUGAR": 55, "AVALON": 30, "AVANTIFEED": 60, "AXISBANK": 70, "BAJAJ-AUTO": 70, "BAJAJCON": 55, "BAJAJELEC": 60,
  "BAJAJFINSV": 70, "BAJAJHLDNG": 60, "BAJFINANCE": 70, "BALAMINES": 60, "BALKRISIND": 70, "BALRAMCHIN": 50,
  "BANCOINDIA": 65, "BANDHANBNK": 50, "BANKBARODA": 70, "BANKINDIA": 65, "BANKBEES": 60, "BARBEQUE": 60, "BATAINDIA": 70,
  "BAYERCROP": 60, "BBTC": 45, "BECTORFOOD": 60, "BEL": 65, "BEML": 55, "BEPL": 50, "BERGEPAINT": 70, "BHARATFORG": 65,
  "BHARTIARTL": 70, "BHEL": 60, "BIKAJI": 35, "BIOCON": 65, "BIRLACORPN": 50, "BIRLANU": 55, "BLS": 40, "BLUEDART": 60,
  "BLUESTARCO": 65, "BODALCHEM": 55, "BOMDYEING": 55, "BOSCHLTD": 70, "BPCL": 65, "BRIGADE": 70, "BRITANNIA": 70,
  "BSOFT": 65, "CAMLINFINE": 55, "CAMPUS": 65, "CAMS": 65, "CANBK": 65, "CANFINHOME": 65, "CAPACITE": 50,
  "CAPLIPOINT": 55, "CARBORUNIV": 60, "CAREATING": 45, "CARTRADE": 50, "CASTROLIND": 60, "CCL": 60, "CEATLTD": 55,
  "CENTENKA": 45, "CENTRALBK": 55, "CENTURYPLY": 60, "CERA": 60, "CESC": 65, "CGCL": 60, "CGPOWER": 60, "CHALET": 60,
  "CHAMBLFERT": 35, "CHEMCON": 55, "CHEMPLASTS": 45, "CHENNPETRO": 55, "CHOLAFIN": 65, "CHOLAHLDNG": 40, "CIEINDIA": 60,
  "CIGNITITEC": 70, "CIPLA": 65, "CLEAN": 65, "CMSINFO": 65, "COALINDIA": 65, "COFORGE": 70, "COLPAL": 65, "CONCOR": 65,
  "CONCORBIO": 35, "COROMANDEL": 70, "CPSE": 45, "CRAFTSMAN": 60, "CREDITACC": 60, "CRISIL": 70, "CROMPTON": 60,
  "CSBBANK": 55, "CUB": 65, "CUMMINSIND": 65, "CYIENT": 60, "DABUR": 70, "DALBHARAT": 70, "DATAPATTNS": 45,
  "DBL": 50, "DCBBANK": 60, "DCMSRIRAM": 60, "DCMSHRIRAM": 60, "DEEPAKNTR": 60, "DELHIVERY": 60, "DELTACORP": 50,
  "DEN": 40, "DEVYANI": 60, "DHAMPURSUG": 45, "DHANUKA": 60, "DIVISLAB": 70, "DLF": 65, "DMART": 65, "DRREDDY": 70,
  "DWARKESH": 50, "EASEMYTRIP": 60, "ECLERX": 70, "EICHERMOT": 60, "EIDPARRY": 60, "EIHOTEL": 50, "ELECON": 50,
  "ELGIEQUIP": 45, "EMAMILTD": 60, "EMBDL": 35, "EMUDHRA": 55, "ENDURANCE": 60, "ENGINERSIN": 55, "ENIL": 50,
  "EPIGRAL": 50, "EPL": 55, "EQUITASBNK": 60, "ERIS": 55, "ESABINDIA": 55, "ESCORTS": 65, "ESTER": 50, "ETERNAL": 60,
  "EVEREADY": 50, "EXCELINDUS": 60, "EXIDEIND": 65, "EXPLEOSOL": 50, "EXXARO": 45, "FACT": 50, "FDC": 60,
  "FEDERALBNK": 70, "FIEMIND": 50, "FILATEX": 50, "FINCABLES": 60, "FINEORG": 60, "FINOPB": 50, "FINPIPE": 55,
  "FIVESTAR": 60, "FLUOROCHEM": 60, "FMCG": 55, "FMGOETZE": 50, "FORTIS": 60, "FSL": 60, "GABRIEL": 60, "GAIL": 65,
  "GALAXYSURF": 50, "GANECOS": 55, "GANESHBE": 55, "GARFIBRES": 60, "GESHIP": 60, "GHCL": 55, "GIPCL": 50,
  "GILLETTE": 65, "GLAND": 50, "GLAXO": 45, "GLENMARK": 65, "GLOBUSSPR": 50, "GMDCLTD": 50, "GMMPFAUDLR": 60,
  "GMRINFRA": 45, "GNFC": 50, "GOCOLORS": 55, "GODREJAGRO": 60, "GODREJCP": 70, "GODREJIND": 45, "GODREJPROP": 65,
  "GOKEX": 55, "GPPL": 60, "GRANULES": 65, "GRAPHITE": 60, "GRASIM": 70, "GREAVESCOT": 50, "GREENPANEL": 60,
  "GREENPLY": 55, "GRINDWELL": 60, "GSFC": 60, "GSPL": 65, "GUJALKALI": 55, "GUJGASLTD": 65, "GULFOILLUB": 50,
  "HAL": 60, "HAPPSTMNDS": 60, "HATHWAY": 55, "HATSUN": 50, "HAVELLS": 70, "HCG": 55, "HCLTECH": 70, "HDFCAMC": 65,
  "HDFCBANK": 70, "HDFCLIFE": 70, "HEIDELBERG": 60, "HEMIPROP": 50, "HEROMOTOCO": 70, "HEUBACHIND": 30, "HFCL": 50,
  "HIKAL": 60, "HIMATSEIDE": 50, "HINDALCO": 65, "HINDCOPPER": 50, "HINDOILEXP": 55, "HINDPETRO": 65, "HINDUNILVR": 70,
  "HOMEFIRST": 45, "HONAUT": 40, "HUHTAMAKI": 50, "ICICIB22": 70, "ICICIBANK": 70, "ICICIGI": 70, "ICICIPRULI": 70,
  "ICIL": 60, "ICRA": 65, "IDBI": 50, "IDFCFIRSTB": 65, "IEX": 45, "IFBIND": 45, "IGL": 50, "IGPL": 45, "INDHOTEL": 65,
  "INDIACEM": 50, "INDIAGLYCO": 55, "INDIAMART": 65, "INDIANB": 60, "INDIGO": 70, "INDIGOPNTS": 65, "INDOCO": 45,
  "INDUSINDBK": 65, "INDUSTOWER": 35, "INFIBEAM": 50, "INFY": 70, "INGERRAND": 45, "INSECTICID": 55, "INTELLECT": 50,
  "IOB": 55, "IOC": 65, "IOLCP": 50, "IONEXCHANG": 55, "IPCALAB": 65, "IPL": 45, "IRB": 50, "IRCON": 50, "IRCTC": 65,
  "IRFC": 55, "ISGEC": 55, "ITC": 70, "ITDCEM": 55, "ITI": 60, "J&KBANK": 55, "JAMNAAUTO": 60, "JAYAGROGN": 50,
  "JBCHEPHARM": 65, "JBMA": 35, "JINDALPOLY": 50, "JINDALSAW": 65, "JINDALSTEL": 65, "JIOFIN": 50, "JKCEMENT": 70,
  "JKL": 50, "JKPAPER": 60, "JKTYRE": 60, "JMFINANCIL": 60, "JSL": 50, "JSWENERGY": 50, "JSWINFRA": 40, "JSWSTEEL": 70,
  "JUBLFOOD": 65, "JUBLINGREA": 60, "JNJ": 45, "JUSTDIAL": 60, "JYOTHYLAB": 65, "KAJARIACER": 60, "KANSAINER": 65,
  "KARURVYSYA": 65, "KAYNES": 30, "KCP": 50, "KEC": 55, "KEI": 60, "KIMS": 60, "KIOCL": 50, "KIRINDUS": 50,
  "KIRLOSBROS": 35, "KNRCON": 45, "KOLTEPATIL": 55, "KOTAKBANK": 70, "KPIL": 55, "KPITTECH": 60, "KPRMILL": 60,
  "KRBL": 50, "KRSNAA": 55, "KSB": 55, "KSCL": 50, "KTKBANK": 60, "LALPATHLAB": 70, "LAOPALA": 60, "LAURUSLABS": 65,
  "LEMONTREE": 60, "LGBBROSLTD": 45, "LICHSGFIN": 65, "LICI": 65, "LINCOLN": 50, "LODHA": 60, "LT": 70, "LTF": 65,
  "LTFOODS": 50, "LTIM": 65, "LUMAXTECH": 45, "LUPIN": 70, "LUXIND": 50, "LXCHEM": 60, "M&M": 65, "M&MFIN": 60,
  "MAGADSUGAR": 50, "MAHABANK": 60, "MAHLIFE": 55, "MAHLOG": 60, "MAHSCOOTER": 60, "MAITHANALL": 55, "MANGLMCEM": 60,
  "MANAPPURAM": 55, "MAPMYINDIA": 45, "MARICO": 70, "MARKSANS": 60, "MARUTI": 70, "MASFIN": 55, "MASTEK": 60,
  "MATRIMONY": 55, "MAXHEALTH": 55, "MAYURUNIQ": 55, "MAZDOCK": 50, "MEDANTA": 55, "MEDPLUS": 45, "METROBRAND": 65,
  "METROPOLIS": 65, "MFSL": 60, "MGL": 65, "MHRIL": 60, "MIDCAPI": 60, "MIDHANI": 60, "MINDACORP": 50, "MOIL": 55,
  "MOL": 50, "MOM100": 60, "MOM50": 65, "MOTHERSON": 60, "MPHASIS": 65, "MPSLTD": 45, "MRF": 70, "MRPL": 50,
  "MSTCLTD": 55, "MSUMI": 70, "MTARTECH": 60, "MUTHOOTFIN": 70, "NAHARINDUS": 50, "NAM-INDIA": 45, "NATCOPHARM": 60,
  "NATIONALUM": 65, "NAUKRI": 65, "NAVINFLUOR": 55, "NAVNETEDUL": 55, "NAZARA": 30, "NCC": 65, "NCLIND": 45,
  "NEOGEN": 55, "NESCO": 70, "NESTLEIND": 70, "NETWORK18": 50, "NEXT50I": 60, "NFL": 55, "NH": 60, "NHPC": 55,
  "NIACL": 55, "NIT": 65, "NIITLTD": 55, "NILKAMAL": 55, "NLCINDIA": 65, "NMDC": 60, "NOCIL": 60, "NRBBEARING": 55,
  "NSLNISP": 60, "NTPC": 70, "NUVOCO": 60, "NYKAA": 50, "OAL": 50, "OBEROIRLTY": 65, "OLECTRA": 45, "ONGC": 65,
  "ORIENTCEM": 45
};

export const MTF_STOCKS: string[] = Object.keys(MTF_MARGINS);

import { INTRADAY_STOCKS as IMPORTED_INTRADAY_STOCKS } from './intradayData';
export const INTRADAY_STOCKS = IMPORTED_INTRADAY_STOCKS;

export const INDICES = [
  "^NSEI",    // NIFTY 50 (Benchmark)
  "^CNX100",  // NIFTY 100 (FNO Stocks)
  "^NSMIDCP", // NIFTY MIDCAP 100
  "BSE-SMLCAP.BO",   // BSE SMALLCAP (Equivalent to NIFTY SMALLCAP 100)
];

export const RAW_UNIVERSE = [...FNO_STOCKS, ...MTF_STOCKS, ...INTRADAY_STOCKS, "^NSEI", "^NSEBANK", "^BSESN"];
export const MARKET_UNIVERSE = [...RAW_UNIVERSE, ...INDICES];
export const NIFTY50 = FNO_STOCKS;

export function getBenchmarkIndex(symbol: string): string {
  if (FNO_STOCKS.includes(symbol)) return "^CNX100";
  if (MTF_STOCKS.includes(symbol)) return "^NSMIDCP";
  if (INTRADAY_STOCKS.includes(symbol)) return "BSE-SMLCAP.BO";
  return "^NSEI";
}
